server:
  port: 8888
spring:
  profile:
    active: native
  application:
    name: ms-configserver
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Softtecnology/service-configuration.git
          clone-on-start: true
          username: ${CONFIG_REPO_USERNAME}
          password: ${CONFIG_REPO_TOKEN}
